### ISSUE TITLE
Volume Permissions Check Needs to Use UID instead of ID

### ISSUE THREAD

**Issue by mattcdavis1** [la-haute-societe/craft-restrict-asset-delete#1] opened 2019-07-22 15:23 UTC
Currently, in `src/actions/DeleteAssets.php` on line 41 the check for permissions is as follows:
```php
if (Craft::$app->getUser()->checkPermission('deleteFilesAndFoldersInVolume:' . $asset->volumeId)) {
````
However, Craft's volume permissions use UIDs so I would suggest the following:

```php
$success = false;
try {
    foreach ($query->all() as $asset) {
        /**
            * @var Asset $asset
            */
        $volume = $asset->getVolume();

        if ($volume && Craft::$app->getUser()->checkPermission('deleteFilesAndFoldersInVolume:' . $volume->uid)) {
            if (Craft::$app->getElements()->deleteElement($asset)) {
                $success = true;
            }
        }
    }
} catch (Exception $exception) {
    $this->setMessage($exception->getMessage());

    return false;
}

if (!$success) {
    $this->setMessage(Craft::t('restrict-asset-delete', 'Some assets were not deleted because they are used.'));
}
else {
    $this->setMessage(Craft::t('app', 'Assets deleted.'));
}

return true;
```

**Comment by nstcactus** [comment] 2021-06-30 10:19
Sorry, I haven't done a good job maintaining this plugin recently. The issue is now fixed by 01dd6095ab64ef9d178c98500cb00bf3ef7e692e, and a new version has been released. Thank you for your help!

**Closed as completed by nstcactus** 2021-06-30 10:19 UTC
